/**:
  ros__parameters:
    multicast_ip: ""
    gnss_port: 10110
    packet_mtu_size: 1500
    launch_hw: true
    setup_sensor: true
    frame_id: hesai
    diag_span: 1000
    min_range: 0.3
    max_range: 300.0
    sync_angle: 0
    cut_angle: 0.0
    sensor_model: PandarQT64
    calibration_file: $(find-pkg-share nebula_decoders)/calibration/hesai/$(var sensor_model).csv
    rotation_speed: 600
    return_mode: Strongest
    ptp_profile: 1588v2
    ptp_domain: 0
    ptp_transport_type: UDP
    ptp_switch_type: TSN
    retry_hw: true
    dual_return_distance_threshold: 0.1
